version: "3.9"

services:
  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    container_name: php
    restart: always
    working_dir: /var/www/symfony
    volumes:
      - ./app:/var/www/symfony
    env_file:
      - .env
  nginx:
    image: nginx:1.23.3-alpine
    container_name: nginx
    restart: always
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./app:/var/www/symfony
      - ./docker/nginx/:/etc/nginx/conf.d
  postgres:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    container_name: postgres
    restart: always
    volumes:
      - symfony-project-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

volumes:
  symfony-project-postgres-data:
