version: "3.9"

services:
  php:
    env_file:
      - docker/env/.env.graphite
  graphite:
    image: graphiteapp/graphite-statsd:1.1.10-4
    container_name: graphite
    restart: always
    volumes:
      - symfony-project-graphite-data:/opt/graphite/storage
    ports:
      - '${GRAPHITE_NGINX:-80}:80'
      - '${GRAPHITE_STATSD:-8125}:8125'

volumes:
  symfony-project-graphite-data:
