version: "3.9"

services:
  php:
    env_file:
      - docker/env/.env.grafana
  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    restart: always
    volumes:
      - symfony-project-grafana-data:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - "${GRAFANA_PORT:-3000}:3000"

volumes:
  symfony-project-grafana-data: