version: "3.9"

services:
  php:
    env_file:
      - docker/env/.env.graphite
  graphite:
    image: graphiteapp/graphite-statsd:1.1.10-4
    container_name: graphite
    restart: always
    volumes:
      - symfony-project-graphite-data:/opt/graphite/storage
    ports:
      - '${GRAPHITE_NGINX:-80}:80'
      - '${GRAPHITE_STATSD:-8125}:8125'
  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    restart: always
    volumes:
      - symfony-project-grafana-data:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - "${GRAFANA_PORT:-3000}:3000"

volumes:
  symfony-project-graphite-data:
  symfony-project-grafana-data: