version: "3.9"

services:
  php:
    env_file:
      - docker/env/.env.influxdb
  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb
    restart: always
    volumes:
      - symfony-project-influxdb-data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USER:-app}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD:-ChangeMe}
      DOCKER_INFLUXDB_INIT_ORG: ${APP_ORG:-app}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET:-default-bucket}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN:-admin_token}
    ports:
      - "${INFLUX_PORT:-8086}:8086"

volumes:
  symfony-project-influxdb-data:
