nelmio_api_doc:
    documentation:
        info:
            title: '%env(APP_NAME)%'
            description: This is a template for a Symfony project with Docker Compose setup, including NGINX, PHP, and PostgreSQL containers. [Read more](https://github.com/JaWitold/symfonyProject)
            version: '%env(APP_VERSION)%'
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc(\.json)?$) # Accepts routes under /api except /api/doc
